SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    CREATE TABLE [dbo].[T015_FacebookCampaign](
        [C015_QueryName] [varchar](50) NULL,
        [C015_Date] [date] NULL,
        [C015_Year] [varchar](255) NULL,
        [C015_YearMonth] [varchar](255) NULL,
        [C015_Month] [varchar](255) NULL,
        [C015_DayofMonth] [varchar](255) NULL,
        [C015_DayofWeek] [varchar](255) NULL,
        [C015_CampaignName] [varchar](255) NULL,
        [C015_CampaignID] [varchar](255) NULL,
        [C015_Account] [varchar](255) NULL,
        [C015_AccountID] [varchar](255) NULL,
        [C015_ImpressionDevice] [varchar](255) NULL,
        [C015_PublisherPlatform] [varchar](255) NULL,
        [C015_PlatformPosition] [varchar](255) NULL,
        [C015_DevicePlatform] [varchar](255) NULL,
        [C015_AccountStatus] [varchar](255) NULL,
        [C015_AccountTimezone] [varchar](255) NULL,
        [C015_CampaignObjective] [varchar](255) NULL,
        [C015_CampaignStatus] [varchar](255) NULL,
        [C015_CampaignBuyingType] [varchar](255) NULL,
        [C015_CampaignStartDate] [varchar](255) NULL,
        [C015_CampaignEndDate] [varchar](255) NULL,
        [C015_CampaignDailyBudget] [float] NULL,
        [C015_CampaignBudgetRemaining] [float] NULL,
        [C015_ReachEstimateMonthlyActiveUsers] [float] NULL,
        [C015_Reach] [float] NULL,
        [C015_Frequency] [float] NULL,
        [C015_Impressions] [float] NULL,
        [C015_Actions] [float] NULL,
        [C015_PeopleTakingAction] [float] NULL,
        [C015_ActionRatePercent] [varchar](255) NULL,
        [C015_PeopleTakingActionRatePercent] [varchar](255) NULL,
        [C015_Cost] [float] NULL,
        [C015_CpmCostPer1000Impressions] [float] NULL,
        [C015_LinkClicks] [float] NULL,
        [C015_UniqueLinkClicks] [float] NULL,
        [C015_CtrLinkClickthroughRate] [varchar](255) NULL,
        [C015_ClicksAll] [float] NULL,
        [C015_UniqueClicksAll] [float] NULL,
        [C015_CtrAll] [varchar](255) NULL,
        [C015_UniqueCtrAll] [varchar](255) NULL,
        [C015_CpcCostPerLinkClick] [float] NULL,
        [C015_CostPerUniqueLinkClick] [float] NULL,
        [C015_CpcAll] [float] NULL,
        [C015_CostPerUniqueClickAll] [float] NULL,
        [C015_PageLikes] [float] NULL,
        [C015_PostComments] [float] NULL,
        [C015_PostEngagements] [float] NULL,
        [C015_PostReactions] [float] NULL,
        [C015_PostSaves] [float] NULL,
        [C015_PostShares] [float] NULL,
        [C015_ThreesecondVideoViews] [float] NULL,
        [C015_UniqueThreesecondVideoViews] [float] NULL,
        [C015_ThirtySecondVideoViews] [float] NULL,
        [C015_VideoWatchesAt25percent] [float] NULL,
        [C015_VideoWatchesAt50percent] [float] NULL,
        [C015_VideoWatchesAt75percent] [float] NULL,
        [C015_VideoWatchesAt95percent] [float] NULL,
        [C015_VideoWatchesAt100percent] [float] NULL,
        [C015_VideoAverageWatchTime] [float] NULL,
        [C015_ClicksToPlayVideo] [float] NULL,
        [C015_ThruplayActions] [float] NULL,
        [C015_UniqueClicksToPlayVideo] [float] NULL,
        [C015_AvgCanvasViewTimeSeconds] [float] NULL,
        [C015_AvgCanvasViewPercentage] [varchar](255) NULL,
        [C015_CostPerThreesecondVideoView] [float] NULL,
        [C015_CostPerThruplay] [float] NULL,
        [C015_WebsiteConversions] [float] NULL,
        [C015_WebsiteConversionRate] [varchar](255) NULL,
        [C015_WebsiteCustomConversions] [float] NULL,
        [C015_WebsiteLeads] [float] NULL,
        [C015_WebsitePurchases] [float] NULL,
        [C015_CostPerWebsiteConversion] [float] NULL,
        [C015_CostPerWebsiteCustomConversions] [float] NULL,
        [C015_CostPerWebsiteLead] [float] NULL,
        [C015_CostPerWebsitePurchase] [float] NULL,
        [C015_CostPerWebsiteSearch] [float] NULL,
        [C015_ConversionsWithin1DayOfView] [float] NULL,
        [C015_ConversionsWithin7DaysOfView] [float] NULL,
        [C015_ConversionsWithin28DaysOfView] [float] NULL,
        [C015_ConversionsWithin1DayOfClick] [float] NULL,
        [C015_ConversionsWithin7DaysOfClick] [float] NULL,
        [C015_ConversionsWithin28DaysOfClick] [float] NULL,
        [C015_LeadsForm] [float] NULL,
        [C015_UniqueLeadsForm] [float] NULL,
        [C015_CostPerLeadForm] [float] NULL,
        [C015_Mkwid] [varchar](255) NULL,
        [C015_Pubcode] [varchar](255) NULL,
        [DateRecordAddedToTable] [datetime2](7) NULL,
        [C015_CampaignVerticle] [char](3) NULL,
        [C015_Adkey] [varchar](255) NULL
    ) ON [PRIMARY]
GO
ALTER TABLE
    [dbo].[T015_FacebookCampaign]
ADD
    DEFAULT (getdate()) FOR [DateRecordAddedToTable]
GO