name: Python Lint and Unit Tests

on: 
  pull_request:
    branches:
      - 'staging'
  
jobs:
  python_format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Black Formatter
        uses: psf/black@stable

  unit_tests:
    needs: python_format
    runs-on: ubuntu-latest
    steps:
      - name: Pytest Goes Here
        # uses: databricks/run-notebook@v0
        run: echo "Unit test placeholder"