name: PR - On Approval DBricks Reminder

on:
  # pull_request_review:
  #   types:
  #     - 'submitted'
  pull_request

jobs:
  staging_comment:
    name: Staging Comment
    # if: |
    #   github.event.review.state == 'approved' ||
    #   startswith(github.event.pull_request.base.ref, 'staging')
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          # github_token:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Workflow comment test'
            })

  # release_comment:
  #   name: Release Comment
  #   # if: |
  #   #   github.event.review.state == 'approved' ||
  #   #   startswith(github.event.pull_request.base.ref, 'release')
  #   environment: production
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: thollander/actions-comment-pull-request@v2
  #       with:
  #         message: |
  #           Before merging to go ${{ vars.DATABRICKS_REPO_URL }} to ensure DBricks Repo is able to pull.