name: PR - On Approval DBricks Reminder

on:
  pull_request_review:
    types:
      - 'submitted'

jobs:
  staging_comment:
    name: Staging Comment
    if: |
      github.event.review.state == 'approved' ||
      startswith(github.event.pull_request.base.ref, 'staging')
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          # github_token:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔔 Before merging to go the [${{ vars.DATABRICKS_REPO_URL }}](DBricks Repo) to ensure there are no pending changes and API pull will be successful 🔔'
            })

  release_comment:
    name: Release Comment
    if: |
      github.event.review.state == 'approved' ||
      startswith(github.event.pull_request.base.ref, 'release')
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          # github_token:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔔 Before merging to go the [${{ vars.DATABRICKS_REPO_URL }}](DBricks Repo) to ensure there are no pending changes and API pull will be successful 🔔'
            })