name: Job Variables Tests

on: 
  pull_request:
    branches:
      - 'staging'
    paths:
      - 'orchestration/**'
  
jobs:
  get_job_file_links:
    runs-on: ubuntu-latest
    environment: development
    outputs:
      matrix: ${{ steps.repo_files.outputs.link_list }}
    steps:
      - name: Get repo job files
        id: repo_files
        run: >
          LINK_LIST=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/pennfoster/databricks-pipelines/pulls/${{ github.event.pull_request.number }}/files | \
            jq -c ['.[] | select((.filename | contains("json")) and (.status != "removed")) | .contents_url'])
            echo "link_list=$LINK_LIST" >> "$GITHUB_OUTPUT"

  assure_correct_job_settings:
    name: Assure Job Settings
    runs-on: ubuntu-latest
    environment: development
    needs: get_job_file_links
    strategy:
      matrix:
        job_content: ${{ fromJson(needs.get_job_file_links.outputs.matrix) }}
    steps:
      - name: Set variables
        id: job_vars
        run: >
          DOWNLOAD_URL=$(curl -L "${{ matrix.job_content }}" | jq -r .download_url);
          JOB_VARS=$(curl -L "$DOWNLOAD_URL");
          echo "job_name=$(echo "$JOB_VARS" | jq -r '.name')" >> "$GITHUB_OUTPUT";
          echo "cicd_tag=$(echo "$JOB_VARS" | jq -r '.tags.workflow')" >> "$GITHUB_OUTPUT";
          echo "task_filepaths='$(echo "$JOB_VARS" | jq -c ['.tasks[].notebook_task.notebook_path'])'" >> "$GITHUB_OUTPUT";
      - name: Assure Correct Tag
        run: >
          if [ "${{ steps.job_vars.outputs.cicd_tag }}" != "CI/CD" ]
            then
              echo "Job ${{ steps.job_vars.outputs.job_name }} is missing required \"workflow: CI/CD\" tag";
              exit 1;
          fi
      - name: Assure Correst Filepaths
        run: >
          for FP in $(echo ${{ steps.job_vars.outputs.task_filepaths }} | jq -r .[]);
            do
              if [[ $FP =~ ^\/Repos\/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\/.*$ ]]
                then
                  echo "In Job ${{ steps.job_vars.outputs.job_name }}:";
                  echo "Notebook filepath is set to personal workspace:";
                  echo $FP;
                  exit 1
              fi
            done
