# Documentation for Databricks specific actions found @ https://github.com/databricks/run-notebook/blob/main/action.yml
name: Update Databricks Jobs

on:
  push:
    branches:
      - master
      - cicd/trigger_new_jobs

jobs:
  pull_latest_commit:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: API post request
        run: |
          curl -L -X PATCH '${{vars.DATABRICKS_HOST}}/api/2.0/repos/${{vars.DATABRICKS_REPO_ID}}' \
          -H 'Authorization: Bearer ${{secrets.DATABRICKS_TOKEN}}' -H 'Content-Type: application/json' -d '{"branch": "master"}'

  update_jobs:
    needs: pull_latest_commit
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
    steps:
      
      - name: Checks out the repo
        uses: actions/checkout@v3
      
      - name: update_jobs
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /Repos/ETL/databricks_pipelines/notebooks/ci_cd/update_env_jobs
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "11.3.x-scala2.12",
              "node_type_id": "Standard_F4"
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
  
      - name: trigger_new_jobs
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /Repos/ETL/databricks_pipelines/notebooks/ci_cd/trigger_updated_jobs
          notebook-params-json: >
            [
              {
                "job_ids": "${{steps.update_jobs.outputs.*}}"
              }
            ]
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "11.3.x-scala2.12",
              "node_type_id": "Standard_F4"
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
