name: Update Databricks Jobs

on:
  push:
    branches:
      - staging

jobs:
  pull_latest_commit:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: API post request
        run: |
          curl -L -X PATCH '${{vars.DATABRICKS_HOST}}/api/2.0/repos/${{vars.DATABRICKS_REPO_ID}}' \
          -H 'Authorization: Bearer ${{secrets.DATABRICKS_TOKEN}}' -H 'Content-Type: application/json' -d '{"branch": "master"}'
  
  update_jobs:
    needs: pull_latest_commit
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
    outputs:
      matrix: ${{ steps.update_jobs.outputs.notebook-output }}
    steps:
# Documentation for Databricks specific actions found @ https://github.com/databricks/run-notebook/blob/main/action.yml    
      - name: Update jobs
        id: update_jobs
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /Repos/ETL/databricks_pipelines/notebooks/ci_cd/update_env_jobs
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "11.3.x-scala2.12",
              "node_type_id": "Standard_F4"
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]

  trigger_jobs:
    needs: update_jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: ${{ fromJson(needs.update_jobs.outputs.matrix) }}
    environment: staging
    steps:
      - name: Trigger Job n
        run: |
          curl -L -X POST '${{vars.DATABRICKS_HOST}}/api/2.1/jobs/run-now' \
          -H 'Authorization: Bearer ${{secrets.DATABRICKS_TOKEN}}' -H 'Content-Type: application/json' -d '{"job_id": "${{ matrix.job_id }}"}'

  start_test_sensore:
    needs: update_jobs
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: >
          echo ${{ needs.update_jobs.outputs.matrix }}