# Documentation for Databricks specific actions found @ https://github.com/databricks/run-notebook/blob/main/action.yml
name: Update Databricks Jobs

on:
  push:
    branches:
      - main
      - master

jobs:
  update_jobs:
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
    steps:
      
      - name: Checks out the repo
        uses: actions/checkout@v3
      
      - name: update_jobs
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /Repos/ETL/notebooks/ci_cd/update_env_jobs.py
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "11.3.x-scala2.12",
              "node_type_id": "Standard_F4"
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
  
      - name: trigger_new_jobs
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: notebooks/ci_cd/trigger_updated_jobs.py
          notebook-params-json: >
            [
              {
                "job_ids": ${{steps.update_jobs.outputs.notebook-output}}
              }
            ]
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "11.3.x-scala2.12",
              "node_type_id": "Standard_F4"
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
<<<<<<< HEAD
            ]
=======
            ]
>>>>>>> master
